services:
  deep-research:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-research
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      # 持久化数据目录映射 - 任务数据
      - ./data/tasks:/app/data/tasks
      # 可选：如果需要持久化其他数据，可以添加更多映射
      - ./data/logs:/app/data/logs
    restart: unless-stopped 
