services:
  deep-research:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-research
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      # 直接目录映射，在启动时修复权限
      - ./data/tasks:/app/data/tasks:rw
      - ./data/logs:/app/data/logs:rw
    restart: unless-stopped
    # 启动时修复权限并启动应用
    command: >
      sh -c "
        # 修复目录权限（允许容器内用户访问）
        chmod -R 755 /app/data/tasks /app/data/logs 2>/dev/null || true &&
        # 启动应用
        node server.js
      "