services:
  deep-research:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-research
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
