services:
  deep-research:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-research
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      # 使用named volumes，避免权限问题
      - deep_research_tasks:/app/data/tasks
      - deep_research_logs:/app/data/logs
    restart: unless-stopped
    # 直接使用nextjs用户运行
    user: "1001:1001"

# named volumes用于数据持久化
volumes:
  deep_research_tasks:
    driver: local
  deep_research_logs:
    driver: local